// تعريف أنواع المباني: التكلفة، تأثيرها الاقتصادي، وأبعادها المجسّمة (3D)
const BUILDING_TYPES = {
  house: {
    id: "house",
    name: "منزل",
    icon: "🏠",
    cost: 50,
    populationCapacity: 4,
    incomePerSec: 0,
    happinessDelta: 0,
    heightMeters: 9,
    footprintMeters: 7,
    color: "#60a5fa",
  },
  market: {
    id: "market",
    name: "سوق",
    icon: "🏪",
    cost: 150,
    populationCapacity: 0,
    incomePerSec: 3,
    happinessDelta: 1,
    heightMeters: 14,
    footprintMeters: 9,
    color: "#f59e0b",
  },
  mosque: {
    id: "mosque",
    name: "مسجد",
    icon: "🕌",
    cost: 100,
    populationCapacity: 0,
    incomePerSec: 0,
    happinessDelta: 4,
    heightMeters: 22,
    footprintMeters: 8,
    color: "#34d399",
  },
  factory: {
    id: "factory",
    name: "مصنع",
    icon: "🏭",
    cost: 300,
    populationCapacity: 0,
    incomePerSec: 9,
    happinessDelta: -3,
    heightMeters: 20,
    footprintMeters: 11,
    color: "#94a3b8",
  },
  park: {
    id: "park",
    name: "حديقة",
    icon: "🌳",
    cost: 80,
    populationCapacity: 0,
    incomePerSec: 0,
    happinessDelta: 3,
    heightMeters: 2,
    footprintMeters: 10,
    color: "#22c55e",
  },
};
